# Change these first
owner: arhippa11 # Your GitHub organization or username, where this repository lives
repo: uptimemonitor # The name of this repository

sites:
  - name: Stocade
    url: https://www.stocade.com
  - name: Store
    url: https://store.stocade.com
  - name: IDK
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.arhippa11.fi
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Monitor - arhippa11
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
